# Mathematics

## Linear Algebra

## Probability Theory and Statistics

### State Bayes law {-}

Bayes law/theorem/rule states that

$$
  P(A|B) = \frac{P(B|A) \: P(A)}{P(B)},
$$
where $P(X|Y)$ is the conditional probability of event X occuring given that Y is true. P(A) and P(B) are called marginal probabilities.

The law can be easily memorised and derived from the symmetric equation

$$
  P(A | B) \: P(B) = P(B | A)\: P(A).
$$

### Explain what a p-value is in the context of an A/B test {-}

When performing an A/B test, our null hypothesis is that group B (the variant) is the same as group A (the control) based on some metric. The result of the experiment measures the difference in the value of the metric between the two groups.

p-value is the probability of observing such a difference or higher if the null hypothesis is true. In other words, if we did an A/A test instead of an A/B test, the probability of observing at least such an extreme result is this p-value.

### Explain what Type I and Type II errors are in the context of an A/B test {-}

Type I error is an error where we reject the null hypothesis when it is actually true. In an A/B test, this is an error where we conclude that we observed an effect in group B (variant) compared to group A (control), when the effect didn't really exist.

Type II error is an error where we fail to reject the null hypothesis when it is actually false. In an A/B test, this is an error where we fail to observe an effect in group B (variant) compared to group A (control), when the effect did exist.

### During a survey with a yes/no answer, and in order to provide anonymity, the participants are asked to answer honestly or not based on the outcome of a coin flip. If the outcome is heads, they should give their true answer, if it is tails they should give a positive/yes answer. Would that work? What are the assumptions? If the result of the survey is that 80% of the participants answered positively, what is the true percentage of positive answers? {-}

Yes this would work because, assuming the coins used are fair (50% chance of heads or tails) and the number of participants is large we easily calculate the true percentage of positive answers.

The flip of the coin affects only the answers of the candidates whose true answer is no/negative.

If $AY$ and $AN$ are the percentages of people that answered yes and no respectively, while $AY$ and $AN$ are the true percentages of yes/no response (the response the candidates would have given if they didn't have to modify their answer), then

$$
  AN = p(heads) \: TN = 0.5 \: TN,
$$
which means that the true percentage of negative answers is

$$
  TN = 2 \:AN = 2 \cdot 0.2 = 0.4 = 40\%,
$$
and therefore the true percentage of positive answers is

$$
  TY = 1 - TN = 1 - 0.4 = 0.6 = 60\%
$$

## Multivariate Calculus
